// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type User struct {
	Username    string    `json:"username"`
	FullName    string    `json:"full_name"`
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
}
